### PR TITLE
Fix recursive includes

### PR DESCRIPTION
**Pull request by clubby789**
Fixing #29 
Leaving this as a draft as it causes `test::asm::include_simple_5` and `test::asm::include_directory_2` to fail. 
```
test::asm::include_simple_5
> test failed -- diagnostics mismatch
> expected 6 messages, got 3

test::asm::include_directory_2
> test failed -- output mismatch
> got:      0x55
> expected: 0x55555555
```

### CODE REVIEW

**Comment by clubby789** [comment]
High diff count is because of accidentally running `cargo fmt`.

**Comment by clubby789** [comment]
The failing tests appear to be because:

- `include_simple_5` expects a file included twice to print two sets of errors
- `include_directory_5` to emit the code of the same file several

This could be fixed in a few ways:
- Updating tests to new behaviour
- Making the tests use multiple files with the same contents, so the result is the same
- Somehow check *specifically* for recursive includes, and not just for duplicated includes
I will implement the first option in my PR, but if I can think of a good approach I'll do the 3rd

**Comment by clubby789** [comment]
I switched to adding an `include_depth` to the parser `State`. Every time a new `include` is performed, I initialize the new `State` with `include_depth + 1`, then panic if the depth exceeds 10. This means that the original tests still work

**Comment by hlorenzi** [comment]
Nice! I believe just checking the include depth is the way to go. Checking by filename would be too restrictive, especially if we're going to have conditional directives later on. (By the way, to make your first attempt pass the tests, I think it would just be a matter of removing the filename from the list after you're finished parsing it, so that it could be included again non-recursively.)

I think a depth of something like 1000 would be more reasonable? Hard to reach in practice, and still not too large for the stack?

Also, are you able to remove the changes made by `cargo fmt`?

**Comment by clubby789** [comment]
I was trying to think of an approach that would actually detect *recursive* includes but that seems overthinking when preventing a certain depth should be enough.

As for the `cargo fmt` changes, I'll just reset and redo the changes; haven't found an 'undo' for `fmt`.

**Pull request closed without merging**
